name: Deploy Assets

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_demo_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

#      - name: Use Node.js 12.x
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12.x
      # Run npm install and build on our code
      - run: cp -r mock-server demo 
      - run: sed -i 's,http://localhost:8082/manifest.json,https://pwa-search-term-injector.herokuapp.com/manifest.json,g' demo/index.html
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=demo --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  deploy_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pwa-search-term-injector:latest

      - name: Build and push version
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pwa-search-term-injector:${{ github.run_number }}

      - name: Update Readme
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPO }}
          short-description: Injects query terms from the current url into progressive web app manifests
          readme-filepath: ./overviews/docker-hub.md
        
